name: BluestarBot
version: '${project.version}'
main: me.lanzhi.bluestarbot.BluestarBotPlugin
api-version: 1.13
commands:
  bluestarbot:
    permission: bluestargame.command
website: https://bluestarbot.lanzhi.me